[[TDLib]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6678511663d5959e9c32f6596cc4743d1a0120cf"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "66014bddfdba9a6c0f8a6f49c8f7b86b8d58cd413b4846b773f1478c82e4e7e2"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.46+0/TDLib.v1.8.46.i686-linux-gnu-cxx03.tar.gz"
[[TDLib]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04280bf2ddbcad7434c541756dda9b95d7501ab2"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "8a21addf590923db745cf67d876c4aa909624ead8128d763f5601a26cef76aa3"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.46+0/TDLib.v1.8.46.i686-linux-gnu-cxx11.tar.gz"
[[TDLib]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd9e84531721a4f3b8a598be37b833650dab539e"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "db3c09a419d4080e230778fa349ca213b235fc3f23a002784322e84022e9693b"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.46+0/TDLib.v1.8.46.x86_64-linux-gnu-cxx03.tar.gz"
[[TDLib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f613b6d57b785e524b3de049d95522d289d8885"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "fc561034f3e25f621282d27eab456344b876f3169876cf5bbfe2fcd70d60b690"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.46+0/TDLib.v1.8.46.x86_64-linux-gnu-cxx11.tar.gz"
[[TDLib]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aea986a341fec3f81fe70aeb07c0123d0e2c87a6"
libc = "musl"
os = "linux"

    [[TDLib.download]]
    sha256 = "d8fb279a0c093ff6b4f10586a30227416b4f2ad00991c90c326b41b3bde86c90"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.46+0/TDLib.v1.8.46.x86_64-linux-musl-cxx03.tar.gz"
[[TDLib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8426f1ef91ee3a9a9c9ec25a6e12be99cec91056"
libc = "musl"
os = "linux"

    [[TDLib.download]]
    sha256 = "9733c9dd3fa395f104b1204c3ba3640722ee00a5760ac89b917c2a0f06bcf655"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.46+0/TDLib.v1.8.46.x86_64-linux-musl-cxx11.tar.gz"
