[[TDLib]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7090edd6e95776e3eca0d9b7438f051461147b66"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "41091aff955e00438c3250597515591b8e2a6cb4d09fa790080d86c0eb21c9e5"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.6.10+0/TDLib.v1.6.10.i686-linux-gnu-cxx03.tar.gz"
[[TDLib]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd215001ac12d3a7791577a788a5d87009c789f9"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "696e09f842b71e558a7a951ded7eead53111261541986d6b6835f0c285cc980f"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.6.10+0/TDLib.v1.6.10.i686-linux-gnu-cxx11.tar.gz"
[[TDLib]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a70ce0e1ef739591c618a23f2169cc1dbd3e9bc5"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "860ce5cd53bdf845e2c80005baac2b35da66c2c3483c7cfa29092b423a52d4fc"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.6.10+0/TDLib.v1.6.10.x86_64-linux-gnu-cxx03.tar.gz"
[[TDLib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73e697b6fa87a2689912400a70cf17db7ee33b16"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "87cf3052acda4c6fa2263356abbcfa39c661a2ab17d9671565a2aca7bb53fb24"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.6.10+0/TDLib.v1.6.10.x86_64-linux-gnu-cxx11.tar.gz"
[[TDLib]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e937b2592e28703ca42c29ed910262e3bde5c404"
libc = "musl"
os = "linux"

    [[TDLib.download]]
    sha256 = "f471485a6e7f1c462fc5f02bec98764a7df37f8006204f7c59c12dea070f3416"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.6.10+0/TDLib.v1.6.10.x86_64-linux-musl-cxx03.tar.gz"
[[TDLib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28ea7737c4781d8017df6cc61c34f5daefacaa4f"
libc = "musl"
os = "linux"

    [[TDLib.download]]
    sha256 = "3f9c4b03930d8d97dc2cc6df39e98c7d4691dbb14c4f52a4d8121fc44ca62f49"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.6.10+0/TDLib.v1.6.10.x86_64-linux-musl-cxx11.tar.gz"
