[[TDLib]]
arch = "aarch64"
git-tree-sha1 = "5209b92aad244e7b819af436ffbcd7b84befbf49"
os = "macos"

    [[TDLib.download]]
    sha256 = "cc8ad302e39d9727e6ac4732ef46b9c332154b1ee0cd0db1f6d6035eab53df35"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.aarch64-apple-darwin.tar.gz"
[[TDLib]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "81ab310c2f61aaff556692662c22f599b737d677"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "08727ab4ff8239a4db02f89bda65b63d72012881c2f59506a489c60b3b7cca71"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.aarch64-linux-gnu-cxx03.tar.gz"
[[TDLib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4bb5e1930b14993d4abca7abb5efee5580669110"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "d377e059d777ae3e14e4f306de96af951ef6e123b138d2ba1607707ed3e26e76"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.aarch64-linux-gnu-cxx11.tar.gz"
[[TDLib]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9bfb96e8e9302064a60657e72aee41c4f095d678"
libc = "musl"
os = "linux"

    [[TDLib.download]]
    sha256 = "69ea29bdc30070b6addb23331170aa0aa09cd9162d8adadc6dc82b75b43d68e7"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.aarch64-linux-musl-cxx03.tar.gz"
[[TDLib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9692fe9287918064b56c3521a814b1987297f261"
libc = "musl"
os = "linux"

    [[TDLib.download]]
    sha256 = "f6ee6fba9bbdc7cb269215f82f536796aa767380797155681a6f0899a108f161"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.aarch64-linux-musl-cxx11.tar.gz"
[[TDLib]]
arch = "aarch64"
git-tree-sha1 = "54712f454f73415a0ad7445f4d4f69c14ff5f0b4"
os = "freebsd"

    [[TDLib.download]]
    sha256 = "2afc30176358c20edbb26da6383d3722d5b611449b94ed3267719f04f086a77f"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.aarch64-unknown-freebsd.tar.gz"
[[TDLib]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7723e5d232f695aedb41c1dd4d6bd8b5b8dcca0"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "17fe3f5bed8e0cc2b052221f37bd8e8be88f08a4c9f808e0007d27cf88fe1dd9"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[TDLib]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57c7c13105782d9f3e9c8122e1038cb1eec716d4"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "6350751712d57b1e8a8d64b23884e841c7b87193e2192871f255e8c264cd70fe"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[TDLib]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a3a9ca369b3f3c9ede625d39828d42c5489caae"
libc = "musl"
os = "linux"

    [[TDLib.download]]
    sha256 = "c9fb9e85dbaf24d40b0f7ebe8e369500745287499bd60d64609b98c0091a14a7"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.armv6l-linux-musleabihf-cxx03.tar.gz"
[[TDLib]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a72c93cc1f64e2858578e1dd3023618d6f3b96c7"
libc = "musl"
os = "linux"

    [[TDLib.download]]
    sha256 = "ab64bb15e18110bd42971a2d07d455f96f59f8d4dac768dc3c3d6b3cd89da27b"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.armv6l-linux-musleabihf-cxx11.tar.gz"
[[TDLib]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d51b80f9c42b53782098bbc74374341e9aa88410"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "f0b0188155f7858ecea7cc0f5aee5499754e9e381bfd4cdd8711f36766cb737d"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[TDLib]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "256d9e9a02592c7da1bc0a55e59d5af323160842"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "0fdb8255a1b759a66d7d46380b9c0309d31eb0cb6f5129a1a19a97d3360ad0e9"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[TDLib]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f1f32529e5223101e2649061d028f630ac08b309"
libc = "musl"
os = "linux"

    [[TDLib.download]]
    sha256 = "5329e5a7b00a18b16d74391fbed56374b4b03d9c6b94a0dcd24368b2d48c8752"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.armv7l-linux-musleabihf-cxx03.tar.gz"
[[TDLib]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9614cc7e5e66d7f7c08d2c9222d5c1740bf54c71"
libc = "musl"
os = "linux"

    [[TDLib.download]]
    sha256 = "7569e53206763cc28491a222d61261f2117f6059868d6fb8707d903cf1100279"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.armv7l-linux-musleabihf-cxx11.tar.gz"
[[TDLib]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a4b185c429784bb878082e10bedf977021dde1c5"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "c9fae70d7ca3ad63e54a291dac71d82128ec656aa63133519486be9b1c293504"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.i686-linux-gnu-cxx03.tar.gz"
[[TDLib]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f473aeb7996febffb7563664028e613c84c532f"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "631ad6a6579f98290789d873650a30bd23f51ade157420945dc24544e3f6c2b8"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.i686-linux-gnu-cxx11.tar.gz"
[[TDLib]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "871afc7b9b7a7ca4b0f39675168a7cc2f32f3684"
libc = "musl"
os = "linux"

    [[TDLib.download]]
    sha256 = "1d6be80f137362885fdbc85703a8ba819fce632a096a0c09d9937c7847b1242a"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.i686-linux-musl-cxx03.tar.gz"
[[TDLib]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b8c9cf59fa8f44918590327047314c432553e8c"
libc = "musl"
os = "linux"

    [[TDLib.download]]
    sha256 = "211cc1d5a3cb6922a30a0735dd08d7cea31e5cb777c935e13f0124e6c28e7d1c"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.i686-linux-musl-cxx11.tar.gz"
[[TDLib]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2bd4579460e620dd7eec148229d0811348da45c3"
os = "windows"

    [[TDLib.download]]
    sha256 = "894a6e064eac0adbabb28df024f9b2bfbd6c1cbf80a733a14af9c591a0609561"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.i686-w64-mingw32-cxx03.tar.gz"
[[TDLib]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a0404f0e923806c7d2c9de2b514ee6ae224b857"
os = "windows"

    [[TDLib.download]]
    sha256 = "b09761ecdf183c57de31b8afe7974c4f074a620e007bfc0d00e1ddf6bdf57697"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.i686-w64-mingw32-cxx11.tar.gz"
[[TDLib]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9520e9c4834517ba76c419c85b61ba68210481d9"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "69d843d77f821be1c7982446e8d5e4251d64a2d63d98c2e888c3b4907f74ea7c"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.powerpc64le-linux-gnu-cxx03.tar.gz"
[[TDLib]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "734f742cb082da1e85cec207c6fb13dfaf5d51cc"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "5638e1a3429a4fe4041c504e753cf5ff868af564500fb14ff7779116b6b84416"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.powerpc64le-linux-gnu-cxx11.tar.gz"
[[TDLib]]
arch = "x86_64"
git-tree-sha1 = "f826ab7b02f52ee692037ad32fc61d834526a085"
os = "macos"

    [[TDLib.download]]
    sha256 = "cefc2adebea3cba346d3c5e7e02508a7e3ba02d6d2e390d53377db2263895a69"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.x86_64-apple-darwin.tar.gz"
[[TDLib]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b7a226177ec02b4a944343daddc2e3fe40859538"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "e2260ebbb65996591a2497535aa7d662e5d331d4f60de06f0b3d7bfe3ef07c28"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.x86_64-linux-gnu-cxx03.tar.gz"
[[TDLib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e47ef722793d2091c911a9904b2883d7957a92dd"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "cd43591906e360f2515eca5b6c8b8c0c250a4241312a43bfbff6ebd6d7a2667c"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.x86_64-linux-gnu-cxx11.tar.gz"
[[TDLib]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7bf7624c02470c1b2846fbb8b62c2c499a029452"
libc = "musl"
os = "linux"

    [[TDLib.download]]
    sha256 = "4e06fb95343cf4a68d03bb78d1fe9696eb1fb59b9bf38f63c6939253551acd10"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.x86_64-linux-musl-cxx03.tar.gz"
[[TDLib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ec873aea2de1dd44f4cb7a71f4ffd4185a197a0"
libc = "musl"
os = "linux"

    [[TDLib.download]]
    sha256 = "ed8c07f72a9e1fd3a48eed91c37fbd4e66163b1e2836d7a4e9533cb804c92439"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.x86_64-linux-musl-cxx11.tar.gz"
[[TDLib]]
arch = "x86_64"
git-tree-sha1 = "82065120eaa84437eca16f9ee95e21fb60760042"
os = "freebsd"

    [[TDLib.download]]
    sha256 = "97ac35f53b3dcb6313c85a9e15eb9b75bc533f5b6054bfdab2b7fb557f722281"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.x86_64-unknown-freebsd.tar.gz"
[[TDLib]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7cf02ae485988a012bbaba0b1fa967d70e2637d5"
os = "windows"

    [[TDLib.download]]
    sha256 = "028446532f38c68c8de5b36204ce03f563d41bbda0a3bcf9e6a286e60bdc79df"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.x86_64-w64-mingw32-cxx03.tar.gz"
[[TDLib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b6ba99339b894494054407916e4cc6cf531360f"
os = "windows"

    [[TDLib.download]]
    sha256 = "a572510a4261a00b9fbe2d4262aad98499e51a8100a7ec27da13f1a54323b24c"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.47+0/TDLib.v1.8.47.x86_64-w64-mingw32-cxx11.tar.gz"
