[[TDLib]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f422939693c434aa977d404b51ab6cc93fb5d10e"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "07177293ecfb5f9ff01ad79c83e02b9e0e867a0d078109ef9e8880de768de6a5"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.0+0/TDLib.v1.8.0.i686-linux-gnu-cxx03.tar.gz"
[[TDLib]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e083d6530f7bdf41a3e033111789e4e0122a566"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "869d652e325ab4cd0652b0b36e333c0af56c1860a2e26513e5f90aa8f097dd11"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.0+0/TDLib.v1.8.0.i686-linux-gnu-cxx11.tar.gz"
[[TDLib]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b3b0452615a5c160fb725a1e83dfd93dcdea491c"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "a622dd8f38586fd196c226dc864b61b4a815c6f99b00e41c5170e3ec8af21abc"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.0+0/TDLib.v1.8.0.x86_64-linux-gnu-cxx03.tar.gz"
[[TDLib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c63d82bdd557af18063cd0c52b1b7885fb5aa3a5"
libc = "glibc"
os = "linux"

    [[TDLib.download]]
    sha256 = "39de53d6c0d651a9c31afdef815e5158dac5019ff526a631a8b45b3447eef32a"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.0+0/TDLib.v1.8.0.x86_64-linux-gnu-cxx11.tar.gz"
[[TDLib]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "877cd6c38a53dcd8bf2c0b9c31c7c957d0f040b6"
libc = "musl"
os = "linux"

    [[TDLib.download]]
    sha256 = "68cf3aeba9bac53d12885677ea0e4a4f131c605bc1100bbc506f69fcd7aa758a"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.0+0/TDLib.v1.8.0.x86_64-linux-musl-cxx03.tar.gz"
[[TDLib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a50b2daefb05c106294762097935c755201c903"
libc = "musl"
os = "linux"

    [[TDLib.download]]
    sha256 = "418bf4645c348239bec7f00da1378ca00287b2d3c48a7e58c675114ae1a2a6ec"
    url = "https://github.com/JuliaBinaryWrappers/TDLib_jll.jl/releases/download/TDLib-v1.8.0+0/TDLib.v1.8.0.x86_64-linux-musl-cxx11.tar.gz"
